
/** biome-ignore-all lint/suspicious/noExplicitAny: we use any to avoid type errors */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import React from "react" 

export const Index: Record<string, any> = {
  "ui": {
    name: "ui",
    description: "",
    type: "registry:ui",
    registryDependencies: ["@audio/cover","@audio/meter","@audio/waveform","@audio/player"],
    files: [undefined],
    component: null,
    categories: undefined,
    meta: undefined,
  },
  "cover": {
    name: "cover",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/ui/cover.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/cover.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "meter": {
    name: "meter",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/ui/meter.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/meter.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "skeleton": {
    name: "skeleton",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/ui/skeleton.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/skeleton.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "waveform": {
    name: "waveform",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/ui/waveform.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/waveform.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "cover-demo": {
    name: "cover-demo",
    description: "Cover with image and fallback",
    type: "registry:example",
    registryDependencies: ["@audio/cover"],
    files: [{
      path: "registry/default/examples/cover-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/examples/cover-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["cover"],
    meta: undefined,
  },
  "cover-fallback": {
    name: "cover-fallback",
    description: "Fallback-only cover",
    type: "registry:example",
    registryDependencies: ["@audio/cover"],
    files: [{
      path: "registry/default/examples/cover-fallback.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/examples/cover-fallback.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["cover"],
    meta: undefined,
  },
  "cover-group": {
    name: "cover-group",
    description: "Overlapping cover group",
    type: "registry:example",
    registryDependencies: ["@audio/cover"],
    files: [{
      path: "registry/default/examples/cover-group.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/examples/cover-group.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["cover","cover group"],
    meta: undefined,
  },
  "cover-radius": {
    name: "cover-radius",
    description: "Covers with different radii",
    type: "registry:example",
    registryDependencies: ["@audio/cover"],
    files: [{
      path: "registry/default/examples/cover-radius.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/examples/cover-radius.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["cover"],
    meta: undefined,
  },
  "cover-size": {
    name: "cover-size",
    description: "Covers with different sizes",
    type: "registry:example",
    registryDependencies: ["@audio/cover"],
    files: [{
      path: "registry/default/examples/cover-size.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/examples/cover-size.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["cover"],
    meta: undefined,
  },
  "meter-demo": {
    name: "meter-demo",
    description: "Basic meter",
    type: "registry:example",
    registryDependencies: ["@audio/meter"],
    files: [{
      path: "registry/default/examples/meter-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/examples/meter-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["meter"],
    meta: undefined,
  },
  "meter-simple": {
    name: "meter-simple",
    description: "Meter without label and value",
    type: "registry:example",
    registryDependencies: ["@audio/meter"],
    files: [{
      path: "registry/default/examples/meter-simple.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/examples/meter-simple.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["meter"],
    meta: undefined,
  },
  "meter-with-formatted-value": {
    name: "meter-with-formatted-value",
    description: "Meter with a custom formatted value",
    type: "registry:example",
    registryDependencies: ["@audio/meter"],
    files: [{
      path: "registry/default/examples/meter-with-formatted-value.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/examples/meter-with-formatted-value.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["meter"],
    meta: undefined,
  },
  "meter-with-range": {
    name: "meter-with-range",
    description: "Meter with min and max values",
    type: "registry:example",
    registryDependencies: ["@audio/meter"],
    files: [{
      path: "registry/default/examples/meter-with-range.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/examples/meter-with-range.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["meter"],
    meta: undefined,
  },
  "audio-player-demo": {
    name: "audio-player-demo",
    description: "Audio player demo",
    type: "registry:example",
    registryDependencies: ["@audio/player","@audio/frame"],
    files: [{
      path: "registry/default/examples/audio-player-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/examples/audio-player-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["player"],
    meta: undefined,
  },
  "waveform-demo": {
    name: "waveform-demo",
    description: "Waveform demo",
    type: "registry:example",
    registryDependencies: ["@audio/waveform"],
    files: [{
      path: "registry/default/examples/waveform-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/examples/waveform-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["waveform"],
    meta: undefined,
  },
  "file-input": {
    name: "file-input",
    description: "Audio file input",
    type: "registry:block",
    registryDependencies: ["@audio/input","@audio/label"],
    files: [{
      path: "registry/default/particles/particle-file-input.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/particles/particle-file-input.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["file"],
    meta: undefined,
  },
  "controls": {
    name: "controls",
    description: "Audio controls",
    type: "registry:block",
    registryDependencies: ["@audio/button","@audio/tooltip","@audio/spinner","audio-engine","lucide-react"],
    files: [{
      path: "registry/default/particles/particle-controls.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/particles/particle-controls.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["controls"],
    meta: undefined,
  },
  "seek-bar": {
    name: "seek-bar",
    description: "Audio seek bar",
    type: "registry:block",
    registryDependencies: ["@audio/slider"],
    files: [{
      path: "registry/default/particles/particle-seek-bar.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/particles/particle-seek-bar.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["seek-bar"],
    meta: undefined,
  },
  "track-info": {
    name: "track-info",
    description: "Audio track info",
    type: "registry:block",
    registryDependencies: ["@audio/cover","@audio/skeleton"],
    files: [{
      path: "registry/default/particles/particle-track-info.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/particles/particle-track-info.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["track-info"],
    meta: undefined,
  },
  "volume": {
    name: "volume",
    description: "Audio volume",
    type: "registry:block",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/particles/particle-volume.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/particles/particle-volume.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["volume"],
    meta: undefined,
  },
  "player": {
    name: "player",
    description: "Audio player",
    type: "registry:block",
    registryDependencies: ["@audio/player"],
    files: [{
      path: "registry/default/particles/particle-player.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/particles/particle-player.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["player"],
    meta: undefined,
  },
  "colors-zinc": {
    name: "colors-zinc",
    description: "",
    type: "registry:style",
    registryDependencies: undefined,
    files: [undefined],
    component: null,
    categories: undefined,
    meta: undefined,
  },
  }