import type { Registry } from "shadcn/schema";

export const examples: Registry["items"] = [
  {
    name: "accordion-controlled",
    description: "Controlled accordion",
    type: "registry:example",
    registryDependencies: ["@audio/accordion", "@audio/button"],
    files: [
      {
        path: "examples/accordion-controlled.tsx",
        type: "registry:example",
      },
    ],
    categories: ["accordion"],
  },
  {
    name: "accordion-demo",
    description: "Basic accordion",
    type: "registry:example",
    registryDependencies: ["@audio/accordion"],
    files: [
      {
        path: "examples/accordion-demo.tsx",
        type: "registry:example",
      },
    ],
    categories: ["accordion"],
  },
  {
    name: "accordion-multiple",
    description: "Accordion allowing multiple panels open",
    type: "registry:example",
    registryDependencies: ["@audio/accordion"],
    files: [
      {
        path: "examples/accordion-multiple.tsx",
        type: "registry:example",
      },
    ],
    categories: ["accordion"],
  },
  {
    name: "accordion-single",
    description: "Accordion with one panel open",
    type: "registry:example",
    registryDependencies: ["@audio/accordion"],
    files: [
      {
        path: "examples/accordion-single.tsx",
        type: "registry:example",
      },
    ],
    categories: ["accordion"],
  },
  {
    name: "alert-demo",
    description: "Basic alert",
    type: "registry:example",
    registryDependencies: ["@audio/alert"],
    files: [
      {
        path: "examples/alert-demo.tsx",
        type: "registry:example",
      },
    ],
    categories: ["alert"],
  },
  {
    name: "alert-with-icon",
    description: "Alert with icon",
    type: "registry:example",
    registryDependencies: ["@audio/alert"],
    files: [
      {
        path: "examples/alert-with-icon.tsx",
        type: "registry:example",
      },
    ],
    categories: ["alert"],
  },
  {
    name: "alert-with-icon-action",
    description: "Alert with icon and action buttons",
    type: "registry:example",
    registryDependencies: ["@audio/alert", "@audio/button"],
    files: [
      {
        path: "examples/alert-with-icon-action.tsx",
        type: "registry:example",
      },
    ],
    categories: ["alert"],
  },
  {
    name: "alert-info",
    description: "Info alert",
    type: "registry:example",
    registryDependencies: ["@audio/alert"],
    files: [
      {
        path: "examples/alert-info.tsx",
        type: "registry:example",
      },
    ],
    categories: ["alert", "info"],
  },
  {
    name: "alert-success",
    description: "Success alert",
    type: "registry:example",
    registryDependencies: ["@audio/alert"],
    files: [
      {
        path: "examples/alert-success.tsx",
        type: "registry:example",
      },
    ],
    categories: ["alert", "success"],
  },
  {
    name: "alert-warning",
    description: "Warning alert",
    type: "registry:example",
    registryDependencies: ["@audio/alert"],
    files: [
      {
        path: "examples/alert-warning.tsx",
        type: "registry:example",
      },
    ],
    categories: ["alert", "warning"],
  },
  {
    name: "alert-error",
    description: "Error alert",
    type: "registry:example",
    registryDependencies: ["@audio/alert"],
    files: [
      {
        path: "examples/alert-error.tsx",
        type: "registry:example",
      },
    ],
    categories: ["alert", "error"],
  },
  {
    name: "alert-dialog-demo",
    description: "Alert dialog",
    type: "registry:example",
    registryDependencies: ["@audio/alert-dialog", "@audio/button"],
    files: [
      {
        path: "examples/alert-dialog-demo.tsx",
        type: "registry:example",
      },
    ],
    categories: ["dialog"],
  },
  {
    name: "autocomplete-demo",
    description: "Basic autocomplete",
    type: "registry:example",
    registryDependencies: ["@audio/autocomplete"],
    files: [
      {
        path: "examples/autocomplete-demo.tsx",
        type: "registry:example",
      },
    ],
    categories: ["autocomplete", "input"],
  },
  {
    name: "autocomplete-disabled",
    description: "Disabled autocomplete",
    type: "registry:example",
    registryDependencies: ["@audio/autocomplete"],
    files: [
      {
        path: "examples/autocomplete-disabled.tsx",
        type: "registry:example",
      },
    ],
    categories: ["autocomplete", "input", "disabled"],
  },
  {
    name: "autocomplete-sm",
    description: "Small autocomplete",
    type: "registry:example",
    registryDependencies: ["@audio/autocomplete"],
    files: [
      {
        path: "examples/autocomplete-sm.tsx",
        type: "registry:example",
      },
    ],
    categories: ["autocomplete", "input"],
  },
  {
    name: "autocomplete-lg",
    description: "Large autocomplete",
    type: "registry:example",
    registryDependencies: ["@audio/autocomplete"],
    files: [
      {
        path: "examples/autocomplete-lg.tsx",
        type: "registry:example",
      },
    ],
    categories: ["autocomplete", "input"],
  },
  {
    name: "autocomplete-with-label",
    description: "Autocomplete with label",
    type: "registry:example",
    registryDependencies: ["@audio/autocomplete", "@audio/label"],
    files: [
      {
        path: "examples/autocomplete-with-label.tsx",
        type: "registry:example",
      },
    ],
    categories: ["autocomplete", "input"],
  },
  {
    name: "autocomplete-inline",
    description: "Autocomplete autofilling the input with the highlighted item",
    type: "registry:example",
    registryDependencies: ["@audio/autocomplete"],
    files: [
      {
        path: "examples/autocomplete-inline.tsx",
        type: "registry:example",
      },
    ],
    categories: ["autocomplete", "input"],
  },
  {
    name: "autocomplete-autohighlight",
    description: "Autocomplete auto highlighting the first option",
    type: "registry:example",
    registryDependencies: ["@audio/autocomplete"],
    files: [
      {
        path: "examples/autocomplete-autohighlight.tsx",
        type: "registry:example",
      },
    ],
    categories: ["autocomplete", "input"],
  },
  {
    name: "autocomplete-with-clear",
    description: "Autocomplete with clear button",
    type: "registry:example",
    registryDependencies: ["@audio/autocomplete"],
    files: [
      {
        path: "examples/autocomplete-with-clear.tsx",
        type: "registry:example",
      },
    ],
    categories: ["autocomplete", "input"],
  },
  {
    name: "autocomplete-with-trigger-clear",
    description: "Autocomplete with trigger and clear buttons",
    type: "registry:example",
    registryDependencies: ["@audio/autocomplete"],
    files: [
      {
        path: "examples/autocomplete-with-trigger-clear.tsx",
        type: "registry:example",
      },
    ],
    categories: ["autocomplete", "input"],
  },
  {
    name: "autocomplete-grouped",
    description: "Autocomplete with grouped items",
    type: "registry:example",
    registryDependencies: ["@audio/autocomplete"],
    files: [
      {
        path: "examples/autocomplete-grouped.tsx",
        type: "registry:example",
      },
    ],
    categories: ["autocomplete", "input"],
  },
  {
    name: "autocomplete-limit",
    description: "Autocomplete with limited number of results",
    type: "registry:example",
    registryDependencies: ["@audio/autocomplete"],
    files: [
      {
        path: "examples/autocomplete-limit.tsx",
        type: "registry:example",
      },
    ],
    categories: ["autocomplete", "input"],
  },
  {
    name: "autocomplete-async",
    description: "Autocomplete with async items loading",
    type: "registry:example",
    registryDependencies: ["@audio/autocomplete"],
    files: [
      {
        path: "examples/autocomplete-async.tsx",
        type: "registry:example",
      },
    ],
    categories: ["autocomplete", "input", "async"],
  },
  {
    name: "autocomplete-form",
    description: "Autocomplete form",
    type: "registry:example",
    registryDependencies: [
      "@audio/autocomplete",
      "@audio/form",
      "@audio/field",
    ],
    files: [
      {
        path: "examples/autocomplete-form.tsx",
        type: "registry:example",
      },
    ],
    categories: ["autocomplete", "input", "form"],
  },
  {
    name: "cover-demo",
    description: "Cover with image and fallback",
    type: "registry:example",
    registryDependencies: ["@audio/cover"],
    files: [
      {
        path: "examples/cover-demo.tsx",
        type: "registry:example",
      },
    ],
    categories: ["cover"],
  },
  {
    name: "cover-fallback",
    description: "Fallback-only cover",
    type: "registry:example",
    registryDependencies: ["@audio/cover"],
    files: [
      {
        path: "examples/cover-fallback.tsx",
        type: "registry:example",
      },
    ],
    categories: ["cover"],
  },
  {
    name: "cover-group",
    description: "Overlapping cover group",
    type: "registry:example",
    registryDependencies: ["@audio/cover"],
    files: [
      {
        path: "examples/cover-group.tsx",
        type: "registry:example",
      },
    ],
    categories: ["cover", "cover group"],
  },
  {
    name: "cover-radius",
    description: "Covers with different radii",
    type: "registry:example",
    registryDependencies: ["@audio/cover"],
    files: [
      {
        path: "examples/cover-radius.tsx",
        type: "registry:example",
      },
    ],
    categories: ["cover"],
  },
  {
    name: "cover-size",
    description: "Covers with different sizes",
    type: "registry:example",
    registryDependencies: ["@audio/cover"],
    files: [
      {
        path: "examples/cover-size.tsx",
        type: "registry:example",
      },
    ],
    categories: ["cover"],
  },
  {
    name: "badge-demo",
    description: "Basic badge",
    type: "registry:example",
    registryDependencies: ["@audio/badge"],
    files: [
      {
        path: "examples/badge-demo.tsx",
        type: "registry:example",
      },
    ],
    categories: ["badge"],
  },
  {
    name: "badge-outline",
    description: "Outline badge",
    type: "registry:example",
    registryDependencies: ["@audio/badge"],
    files: [
      {
        path: "examples/badge-outline.tsx",
        type: "registry:example",
      },
    ],
    categories: ["badge"],
  },
  {
    name: "badge-secondary",
    description: "Secondary badge",
    type: "registry:example",
    registryDependencies: ["@audio/badge"],
    files: [
      {
        path: "examples/badge-secondary.tsx",
        type: "registry:example",
      },
    ],
    categories: ["badge"],
  },
  {
    name: "badge-destructive",
    description: "Destructive badge",
    type: "registry:example",
    registryDependencies: ["@audio/badge"],
    files: [
      {
        path: "examples/badge-destructive.tsx",
        type: "registry:example",
      },
    ],
    categories: ["badge", "destructive", "error"],
  },
  {
    name: "badge-info",
    description: "Info badge",
    type: "registry:example",
    registryDependencies: ["@audio/badge"],
    files: [
      {
        path: "examples/badge-info.tsx",
        type: "registry:example",
      },
    ],
    categories: ["badge", "info"],
  },
  {
    name: "badge-success",
    description: "Success badge",
    type: "registry:example",
    registryDependencies: ["@audio/badge"],
    files: [
      {
        path: "examples/badge-success.tsx",
        type: "registry:example",
      },
    ],
    categories: ["badge", "success"],
  },
  {
    name: "badge-warning",
    description: "Warning badge",
    type: "registry:example",
    registryDependencies: ["@audio/badge"],
    files: [
      {
        path: "examples/badge-warning.tsx",
        type: "registry:example",
      },
    ],
    categories: ["badge", "warning"],
  },
  {
    name: "badge-error",
    description: "Error badge",
    type: "registry:example",
    registryDependencies: ["@audio/badge"],
    files: [
      {
        path: "examples/badge-error.tsx",
        type: "registry:example",
      },
    ],
    categories: ["badge", "error"],
  },
  {
    name: "badge-sm",
    description: "Small badge",
    type: "registry:example",
    registryDependencies: ["@audio/badge"],
    files: [
      {
        path: "examples/badge-sm.tsx",
        type: "registry:example",
      },
    ],
    categories: ["badge"],
  },
  {
    name: "badge-lg",
    description: "Large badge",
    type: "registry:example",
    registryDependencies: ["@audio/badge"],
    files: [
      {
        path: "examples/badge-lg.tsx",
        type: "registry:example",
      },
    ],
    categories: ["badge"],
  },
  {
    name: "badge-with-icon",
    description: "Badge with icon",
    type: "registry:example",
    registryDependencies: ["@audio/badge"],
    files: [
      {
        path: "examples/badge-with-icon.tsx",
        type: "registry:example",
      },
    ],
    categories: ["badge"],
  },
  {
    name: "badge-with-link",
    description: "Badge with link",
    type: "registry:example",
    registryDependencies: ["@audio/badge"],
    files: [
      {
        path: "examples/badge-with-link.tsx",
        type: "registry:example",
      },
    ],
    categories: ["badge"],
  },
  {
    name: "breadcrumb-demo",
    description: "Breadcrumb with menu example",
    type: "registry:example",
    registryDependencies: ["@audio/breadcrumb", "@audio/menu"],
    files: [{ path: "examples/breadcrumb-demo.tsx", type: "registry:example" }],
    categories: ["breadcrumb", "menu"],
  },
  {
    name: "breadcrumb-custom-separator",
    description: "Breadcrumb with custom separator",
    type: "registry:example",
    registryDependencies: ["@audio/breadcrumb"],
    files: [
      {
        path: "examples/breadcrumb-custom-separator.tsx",
        type: "registry:example",
      },
    ],
    categories: ["breadcrumb"],
  },
  {
    name: "button-demo",
    description: "Default button",
    type: "registry:example",
    registryDependencies: ["@audio/button"],
    files: [
      {
        path: "examples/button-demo.tsx",
        type: "registry:example",
      },
    ],
    categories: ["button"],
  },
  {
    name: "button-secondary",
    description: "Secondary button",
    type: "registry:example",
    registryDependencies: ["@audio/button"],
    files: [
      {
        path: "examples/button-secondary.tsx",
        type: "registry:example",
      },
    ],
    categories: ["button"],
  },
  {
    name: "button-destructive",
    description: "Destructive button",
    type: "registry:example",
    registryDependencies: ["@audio/button"],
    files: [
      {
        path: "examples/button-destructive.tsx",
        type: "registry:example",
      },
    ],
    categories: ["button", "delete", "destructive"],
  },
  {
    name: "button-destructive-outline",
    description: "Destructive outline button",
    type: "registry:example",
    registryDependencies: ["@audio/button"],
    files: [
      {
        path: "examples/button-destructive-outline.tsx",
        type: "registry:example",
      },
    ],
    categories: ["button", "delete"],
  },
  {
    name: "button-outline",
    description: "Outline button",
    type: "registry:example",
    registryDependencies: ["@audio/button"],
    files: [{ path: "examples/button-outline.tsx", type: "registry:example" }],
    categories: ["button"],
  },
  {
    name: "button-ghost",
    description: "Ghost button",
    type: "registry:example",
    registryDependencies: ["@audio/button"],
    files: [{ path: "examples/button-ghost.tsx", type: "registry:example" }],
    categories: ["button"],
  },
  {
    name: "button-link",
    description: "Link button",
    type: "registry:example",
    registryDependencies: ["@audio/button"],
    files: [{ path: "examples/button-link.tsx", type: "registry:example" }],
    categories: ["button"],
  },
  {
    name: "button-xs",
    description: "Extra-small button",
    type: "registry:example",
    registryDependencies: ["@audio/button"],
    files: [{ path: "examples/button-xs.tsx", type: "registry:example" }],
    categories: ["button"],
  },
  {
    name: "button-sm",
    description: "Small button",
    type: "registry:example",
    registryDependencies: ["@audio/button"],
    files: [{ path: "examples/button-sm.tsx", type: "registry:example" }],
    categories: ["button"],
  },
  {
    name: "button-lg",
    description: "Large button",
    type: "registry:example",
    registryDependencies: ["@audio/button"],
    files: [{ path: "examples/button-lg.tsx", type: "registry:example" }],
    categories: ["button"],
  },
  {
    name: "button-xl",
    description: "Extra-large button",
    type: "registry:example",
    registryDependencies: ["@audio/button"],
    files: [{ path: "examples/button-xl.tsx", type: "registry:example" }],
    categories: ["button"],
  },
  {
    name: "button-disabled",
    description: "Disabled button",
    type: "registry:example",
    registryDependencies: ["@audio/button"],
    files: [{ path: "examples/button-disabled.tsx", type: "registry:example" }],
    categories: ["button", "disabled"],
  },
  {
    name: "button-icon",
    description: "Icon button",
    type: "registry:example",
    registryDependencies: ["@audio/button"],
    files: [{ path: "examples/button-icon.tsx", type: "registry:example" }],
    categories: ["button"],
  },
  {
    name: "button-icon-sm",
    description: "Small icon button",
    type: "registry:example",
    registryDependencies: ["@audio/button"],
    files: [{ path: "examples/button-icon-sm.tsx", type: "registry:example" }],
    categories: ["button"],
  },
  {
    name: "button-icon-lg",
    description: "Large icon button",
    type: "registry:example",
    registryDependencies: ["@audio/button"],
    files: [{ path: "examples/button-icon-lg.tsx", type: "registry:example" }],
    categories: ["button"],
  },
  {
    name: "button-with-icon",
    description: "Button with icon",
    type: "registry:example",
    registryDependencies: ["@audio/button"],
    files: [
      { path: "examples/button-with-icon.tsx", type: "registry:example" },
    ],
    categories: ["button"],
  },
  {
    name: "button-with-link",
    description: "Link rendered as button",
    type: "registry:example",
    registryDependencies: ["@audio/button"],
    files: [
      { path: "examples/button-with-link.tsx", type: "registry:example" },
    ],
    categories: ["button"],
  },
  {
    name: "button-loading",
    description: "Loading button",
    type: "registry:example",
    registryDependencies: ["@audio/button"],
    files: [{ path: "examples/button-loading.tsx", type: "registry:example" }],
    categories: ["button", "loading"],
  },
  {
    name: "card-demo",
    description: "Card example with form",
    type: "registry:example",
    registryDependencies: [
      "@audio/card",
      "@audio/button",
      "@audio/select",
      "@audio/form",
      "@audio/field",
    ],
    files: [
      {
        path: "examples/card-demo.tsx",
        type: "registry:example",
      },
    ],
    categories: ["card", "button", "input", "select", "form", "field"],
  },
  {
    name: "checkbox-card",
    description: "Card-style checkbox",
    type: "registry:example",
    registryDependencies: ["@audio/checkbox", "@audio/label"],
    files: [{ path: "examples/checkbox-card.tsx", type: "registry:example" }],
    categories: ["checkbox", "card", "label"],
  },
  {
    name: "checkbox-demo",
    description: "Basic checkbox",
    type: "registry:example",
    registryDependencies: ["@audio/checkbox", "@audio/label"],
    files: [{ path: "examples/checkbox-demo.tsx", type: "registry:example" }],
    categories: ["checkbox", "label"],
  },
  {
    name: "checkbox-disabled",
    description: "Disabled checkbox",
    type: "registry:example",
    registryDependencies: ["@audio/checkbox", "@audio/label"],
    files: [
      { path: "examples/checkbox-disabled.tsx", type: "registry:example" },
    ],
    categories: ["checkbox", "disabled", "label"],
  },
  {
    name: "checkbox-form",
    description: "Checkbox in a form",
    type: "registry:example",
    registryDependencies: [
      "@audio/checkbox",
      "@audio/field",
      "@audio/form",
      "@audio/button",
    ],
    files: [{ path: "examples/checkbox-form.tsx", type: "registry:example" }],
    categories: ["checkbox", "form", "button", "label"],
  },
  {
    name: "checkbox-group-demo",
    description: "Checkbox group",
    type: "registry:example",
    registryDependencies: [
      "@audio/checkbox-group",
      "@audio/checkbox",
      "@audio/label",
    ],
    files: [
      { path: "examples/checkbox-group-demo.tsx", type: "registry:example" },
    ],
    categories: ["checkbox group", "checkbox"],
  },
  {
    name: "checkbox-group-disabled",
    description: "Checkbox group with disabled item",
    type: "registry:example",
    registryDependencies: [
      "@audio/checkbox-group",
      "@audio/checkbox",
      "@audio/label",
    ],
    files: [
      {
        path: "examples/checkbox-group-disabled.tsx",
        type: "registry:example",
      },
    ],
    categories: ["checkbox group", "checkbox", "disabled"],
  },
  {
    name: "checkbox-group-form",
    description: "Checkbox group in a form",
    type: "registry:example",
    registryDependencies: [
      "@audio/checkbox-group",
      "@audio/checkbox",
      "@audio/button",
      "@audio/field",
      "@audio/fieldset",
      "@audio/form",
    ],
    files: [
      { path: "examples/checkbox-group-form.tsx", type: "registry:example" },
    ],
    categories: [
      "checkbox group",
      "checkbox",
      "form",
      "button",
      "field",
      "fieldset",
    ],
  },
  {
    name: "checkbox-group-nested-parent",
    description: "Checkbox group parent with nested children controls",
    type: "registry:example",
    registryDependencies: [
      "@audio/checkbox-group",
      "@audio/checkbox",
      "@audio/label",
    ],
    files: [
      {
        path: "examples/checkbox-group-nested-parent.tsx",
        type: "registry:example",
      },
    ],
    categories: ["checkbox group", "checkbox", "label"],
  },
  {
    name: "checkbox-group-parent",
    description: "Checkbox group select/deselect all checkboxes",
    type: "registry:example",
    registryDependencies: [
      "@audio/checkbox-group",
      "@audio/checkbox",
      "@audio/label",
    ],
    files: [
      { path: "examples/checkbox-group-parent.tsx", type: "registry:example" },
    ],
    categories: ["checkbox group", "checkbox", "label"],
  },
  {
    name: "checkbox-with-description",
    description: "Checkbox with helper text",
    type: "registry:example",
    registryDependencies: ["@audio/checkbox", "@audio/label"],
    files: [
      {
        path: "examples/checkbox-with-description.tsx",
        type: "registry:example",
      },
    ],
    categories: ["checkbox", "label", "helper", "hint"],
  },
  {
    name: "collapsible-demo",
    description: "Basic collapsible",
    type: "registry:example",
    registryDependencies: ["@audio/collapsible"],
    files: [
      { path: "examples/collapsible-demo.tsx", type: "registry:example" },
    ],
    categories: ["collapsible"],
  },
  {
    name: "combobox-demo",
    description: "Basic combobox",
    type: "registry:example",
    registryDependencies: ["@audio/combobox"],
    files: [{ path: "examples/combobox-demo.tsx", type: "registry:example" }],
    categories: ["combobox", "input"],
  },
  {
    name: "combobox-disabled",
    description: "Disabled combobox",
    type: "registry:example",
    registryDependencies: ["@audio/combobox"],
    files: [
      { path: "examples/combobox-disabled.tsx", type: "registry:example" },
    ],
    categories: ["combobox", "input", "disabled"],
  },
  {
    name: "combobox-sm",
    description: "Small combobox",
    type: "registry:example",
    registryDependencies: ["@audio/combobox"],
    files: [{ path: "examples/combobox-sm.tsx", type: "registry:example" }],
    categories: ["combobox", "input"],
  },
  {
    name: "combobox-lg",
    description: "Large combobox",
    type: "registry:example",
    registryDependencies: ["@audio/combobox"],
    files: [{ path: "examples/combobox-lg.tsx", type: "registry:example" }],
    categories: ["combobox", "input"],
  },
  {
    name: "combobox-with-label",
    description: "Combobox with label",
    type: "registry:example",
    registryDependencies: ["@audio/combobox", "@audio/label"],
    files: [
      { path: "examples/combobox-with-label.tsx", type: "registry:example" },
    ],
    categories: ["combobox", "input"],
  },
  {
    name: "combobox-autohighlight",
    description: "Combobox auto highlighting the first option",
    type: "registry:example",
    registryDependencies: ["@audio/combobox"],
    files: [
      { path: "examples/combobox-autohighlight.tsx", type: "registry:example" },
    ],
    categories: ["combobox", "input"],
  },
  {
    name: "combobox-grouped",
    description: "Combobox with grouped items",
    type: "registry:example",
    registryDependencies: ["@audio/combobox"],
    files: [
      { path: "examples/combobox-grouped.tsx", type: "registry:example" },
    ],
    categories: ["combobox", "input"],
  },
  {
    name: "combobox-with-clear",
    description: "Combobox with clear button",
    type: "registry:example",
    registryDependencies: ["@audio/combobox"],
    files: [
      { path: "examples/combobox-with-clear.tsx", type: "registry:example" },
    ],
    categories: ["combobox", "input"],
  },
  {
    name: "combobox-multiple",
    description: "Combobox with multiple selection",
    type: "registry:example",
    registryDependencies: ["@audio/combobox"],
    files: [
      { path: "examples/combobox-multiple.tsx", type: "registry:example" },
    ],
    categories: ["combobox", "input"],
  },
  {
    name: "combobox-with-inner-input",
    description: "Combobox with popup",
    type: "registry:example",
    registryDependencies: ["@audio/combobox", "@audio/button"],
    files: [
      {
        path: "examples/combobox-with-inner-input.tsx",
        type: "registry:example",
      },
    ],
    categories: ["combobox", "input"],
  },
  {
    name: "combobox-form",
    description: "Combobox form",
    type: "registry:example",
    registryDependencies: [
      "@audio/combobox",
      "@audio/button",
      "@audio/form",
      "@audio/field",
    ],
    files: [{ path: "examples/combobox-form.tsx", type: "registry:example" }],
    categories: ["combobox", "input", "form"],
  },
  {
    name: "combobox-multiple-form",
    description: "Combobox multiple selection form",
    type: "registry:example",
    registryDependencies: [
      "@audio/combobox",
      "@audio/button",
      "@audio/form",
      "@audio/field",
    ],
    files: [
      { path: "examples/combobox-multiple-form.tsx", type: "registry:example" },
    ],
    categories: ["combobox", "input", "form", "multiple"],
  },
  {
    name: "dialog-close-confirmation",
    description: "Prompt before closing with unsaved changes",
    type: "registry:example",
    registryDependencies: [
      "@audio/alert-dialog",
      "@audio/dialog",
      "@audio/button",
      "@audio/form",
      "@audio/field",
      "@audio/textarea",
    ],
    files: [
      {
        path: "examples/dialog-close-confirmation.tsx",
        type: "registry:example",
      },
    ],
    categories: [
      "dialog",
      "alert dialog",
      "form",
      "field",
      "button",
      "textarea",
    ],
  },
  {
    name: "dialog-demo",
    description: "Basic dialog",
    type: "registry:example",
    registryDependencies: [
      "@audio/dialog",
      "@audio/button",
      "@audio/form",
      "@audio/field",
    ],
    files: [{ path: "examples/dialog-demo.tsx", type: "registry:example" }],
    categories: ["dialog", "form", "field", "button"],
  },
  {
    name: "dialog-from-menu",
    description: "Open dialog from a menu item",
    type: "registry:example",
    registryDependencies: ["@audio/dialog", "@audio/menu", "@audio/button"],
    files: [
      { path: "examples/dialog-from-menu.tsx", type: "registry:example" },
    ],
    categories: ["dialog", "menu", "button"],
  },
  {
    name: "dialog-nested",
    description: "Dialog with a nested dialog",
    type: "registry:example",
    registryDependencies: ["@audio/dialog", "@audio/button", "@audio/field"],
    files: [{ path: "examples/dialog-nested.tsx", type: "registry:example" }],
    categories: ["dialog", "field", "button"],
  },
  {
    name: "sheet-demo",
    description: "Basic sheet",
    type: "registry:example",
    registryDependencies: [
      "@audio/sheet",
      "@audio/button",
      "@audio/form",
      "@audio/field",
    ],
    files: [{ path: "examples/sheet-demo.tsx", type: "registry:example" }],
    categories: ["sheet", "dialog"],
  },
  {
    name: "sheet-position",
    description: "Sheet position",
    type: "registry:example",
    registryDependencies: ["@audio/sheet", "@audio/button"],
    files: [{ path: "examples/sheet-position.tsx", type: "registry:example" }],
    categories: ["sheet"],
  },
  {
    name: "field-checkbox",
    description: "Field with checkbox",
    type: "registry:example",
    registryDependencies: ["@audio/field", "@audio/checkbox"],
    files: [{ path: "examples/field-checkbox.tsx", type: "registry:example" }],
    categories: ["field", "label", "checkbox"],
  },
  {
    name: "field-checkbox-group",
    description: "Field with checkbox group",
    type: "registry:example",
    registryDependencies: [
      "@audio/field",
      "@audio/checkbox-group",
      "@audio/checkbox",
      "@audio/fieldset",
    ],
    files: [
      { path: "examples/field-checkbox-group.tsx", type: "registry:example" },
    ],
    categories: ["field", "checkbox group", "checkbox", "fieldset", "label"],
  },
  {
    name: "field-complete-form",
    description: "Complete form built with field",
    type: "registry:example",
    registryDependencies: [
      "@audio/field",
      "@audio/select",
      "@audio/checkbox",
      "@audio/form",
      "@audio/button",
    ],
    files: [
      { path: "examples/field-complete-form.tsx", type: "registry:example" },
    ],
    categories: [
      "field",
      "label",
      "form",
      "select",
      "checkbox",
      "button",
      "helper",
      "hint",
    ],
  },
  {
    name: "field-demo",
    description: "Field with description",
    type: "registry:example",
    registryDependencies: ["@audio/field"],
    files: [{ path: "examples/field-demo.tsx", type: "registry:example" }],
    categories: ["field", "label", "helper", "hint"],
  },
  {
    name: "field-disabled",
    description: "Field in disabled state",
    type: "registry:example",
    registryDependencies: ["@audio/field"],
    files: [{ path: "examples/field-disabled.tsx", type: "registry:example" }],
    categories: ["field", "label", "disabled", "helper", "hint"],
  },
  {
    name: "field-error",
    description: "Field showing validation error",
    type: "registry:example",
    registryDependencies: ["@audio/field"],
    files: [{ path: "examples/field-error.tsx", type: "registry:example" }],
    categories: ["field", "label", "error"],
  },
  {
    name: "field-autocomplete",
    description: "Field with autocomplete",
    type: "registry:example",
    registryDependencies: ["@audio/field", "@audio/autocomplete"],
    files: [
      { path: "examples/field-autocomplete.tsx", type: "registry:example" },
    ],
    categories: ["field", "input", "autocomplete", "label"],
  },
  {
    name: "field-combobox",
    description: "Field with combobox",
    type: "registry:example",
    registryDependencies: ["@audio/field", "@audio/combobox"],
    files: [{ path: "examples/field-combobox.tsx", type: "registry:example" }],
    categories: ["field", "input", "combobox", "label"],
  },
  {
    name: "field-combobox-multiple",
    description: "Field with multiple selection combobox",
    type: "registry:example",
    registryDependencies: ["@audio/field", "@audio/combobox"],
    files: [
      {
        path: "examples/field-combobox-multiple.tsx",
        type: "registry:example",
      },
    ],
    categories: ["field", "input", "combobox", "label", "multiple"],
  },
  {
    name: "field-number-field",
    description: "Field with number field",
    type: "registry:example",
    registryDependencies: ["@audio/field", "@audio/number-field"],
    files: [
      { path: "examples/field-number-field.tsx", type: "registry:example" },
    ],
    categories: ["field", "input", "label", "number", "helper", "hint"],
  },
  {
    name: "field-radio",
    description: "Field with radio group",
    type: "registry:example",
    registryDependencies: [
      "@audio/field",
      "@audio/radio-group",
      "@audio/fieldset",
    ],
    files: [{ path: "examples/field-radio.tsx", type: "registry:example" }],
    categories: ["field", "radio", "label", "fieldset", "helper", "hint"],
  },
  {
    name: "field-required",
    description: "Field with required indicator",
    type: "registry:example",
    registryDependencies: ["@audio/field"],
    files: [{ path: "examples/field-required.tsx", type: "registry:example" }],
    categories: ["field", "label", "required"],
  },
  {
    name: "field-select",
    description: "Field with select",
    type: "registry:example",
    registryDependencies: ["@audio/field", "@audio/select"],
    files: [{ path: "examples/field-select.tsx", type: "registry:example" }],
    categories: ["field", "select", "label", "helper", "hint"],
  },
  {
    name: "field-slider",
    description: "Field with slider",
    type: "registry:example",
    registryDependencies: ["@audio/field", "@audio/slider"],
    files: [{ path: "examples/field-slider.tsx", type: "registry:example" }],
    categories: ["field", "slider", "label", "helper", "hint"],
  },
  {
    name: "field-switch",
    description: "Field with toggle switch",
    type: "registry:example",
    registryDependencies: ["@audio/field", "@audio/switch"],
    files: [{ path: "examples/field-switch.tsx", type: "registry:example" }],
    categories: ["field", "switch", "label"],
  },
  {
    name: "field-textarea",
    description: "Field with textarea",
    type: "registry:example",
    registryDependencies: ["@audio/field", "@audio/textarea"],
    files: [{ path: "examples/field-textarea.tsx", type: "registry:example" }],
    categories: ["field", "textarea", "label", "helper", "hint"],
  },
  {
    name: "field-validity",
    description: "Show field validity state",
    type: "registry:example",
    registryDependencies: ["@audio/field"],
    files: [{ path: "examples/field-validity.tsx", type: "registry:example" }],
    categories: ["field"],
  },
  {
    name: "fieldset-demo",
    description: "Fieldset with legend and labeled fields",
    type: "registry:example",
    registryDependencies: ["@audio/fieldset", "@audio/field"],
    files: [{ path: "examples/fieldset-demo.tsx", type: "registry:example" }],
    categories: ["fieldset", "field", "label", "input", "helper"],
  },
  {
    name: "form-demo",
    description: "Input in a form",
    type: "registry:example",
    registryDependencies: ["@audio/form", "@audio/field", "@audio/button"],
    files: [
      {
        path: "examples/form-demo.tsx",
        type: "registry:example",
      },
    ],
    categories: ["form", "field", "button", "input"],
  },
  {
    name: "form-zod",
    description: "Form with zod validation",
    type: "registry:example",
    registryDependencies: ["@audio/form", "@audio/field", "@audio/button"],
    dependencies: ["zod"],
    files: [{ path: "examples/form-zod.tsx", type: "registry:example" }],
    categories: ["form", "field", "button", "validation", "label", "zod"],
  },
  {
    name: "empty-demo",
    description: "Basic empty state with icon",
    type: "registry:example",
    registryDependencies: ["@audio/empty", "@audio/button"],
    files: [{ path: "examples/empty-demo.tsx", type: "registry:example" }],
    categories: ["empty"],
  },
  {
    name: "input-demo",
    description: "Basic input component without label",
    type: "registry:example",
    registryDependencies: ["@audio/input"],
    files: [
      {
        path: "examples/input-demo.tsx",
        type: "registry:example",
      },
    ],
    categories: ["input"],
  },
  {
    name: "frame-demo",
    description: "Frame example",
    type: "registry:example",
    registryDependencies: ["@audio/frame"],
    files: [{ path: "examples/frame-demo.tsx", type: "registry:example" }],
    categories: ["frame"],
  },
  {
    name: "group-demo",
    description: "Group example",
    type: "registry:example",
    registryDependencies: ["@audio/group", "@audio/button"],
    files: [{ path: "examples/group-demo.tsx", type: "registry:example" }],
    categories: ["group"],
  },
  {
    name: "group-with-input",
    description: "Group with input",
    type: "registry:example",
    registryDependencies: ["@audio/group", "@audio/button", "@audio/input"],
    files: [
      { path: "examples/group-with-input.tsx", type: "registry:example" },
    ],
    categories: ["group"],
  },
  {
    name: "input-sm",
    description: "Small input",
    type: "registry:example",
    registryDependencies: ["@audio/input"],
    files: [{ path: "examples/input-sm.tsx", type: "registry:example" }],
    categories: ["input"],
  },
  {
    name: "input-lg",
    description: "Large input",
    type: "registry:example",
    registryDependencies: ["@audio/input"],
    files: [{ path: "examples/input-lg.tsx", type: "registry:example" }],
    categories: ["input"],
  },
  {
    name: "input-disabled",
    description: "Input with disabled state",
    type: "registry:example",
    registryDependencies: ["@audio/input"],
    files: [
      {
        path: "examples/input-disabled.tsx",
        type: "registry:example",
      },
    ],
    categories: ["input", "disabled"],
  },
  {
    name: "input-file",
    description: "Input type set to file",
    type: "registry:example",
    registryDependencies: ["@audio/input"],
    files: [
      {
        path: "examples/input-file.tsx",
        type: "registry:example",
      },
    ],
    categories: ["input", "file"],
  },
  {
    name: "input-with-label",
    description: "Input with label",
    type: "registry:example",
    registryDependencies: ["@audio/input", "@audio/label"],
    files: [
      {
        path: "examples/input-with-label.tsx",
        type: "registry:example",
      },
    ],
    categories: ["input", "label"],
  },
  {
    name: "input-with-button",
    description: "Input with button",
    type: "registry:example",
    registryDependencies: ["@audio/input", "@audio/button"],
    files: [
      {
        path: "examples/input-with-button.tsx",
        type: "registry:example",
      },
    ],
    categories: ["input", "button"],
  },
  {
    name: "menu-checkbox",
    description: "Menu with checkbox items",
    type: "registry:example",
    registryDependencies: ["@audio/menu", "@audio/button"],
    files: [{ path: "examples/menu-checkbox.tsx", type: "registry:example" }],
    categories: ["menu", "checkbox"],
  },
  {
    name: "menu-close-on-click",
    description: "Close menu when items are clicked",
    type: "registry:example",
    registryDependencies: ["@audio/menu", "@audio/button"],
    files: [
      { path: "examples/menu-close-on-click.tsx", type: "registry:example" },
    ],
    categories: ["menu"],
  },
  {
    name: "menu-demo",
    description: "Basic menu",
    type: "registry:example",
    registryDependencies: ["@audio/menu", "@audio/button"],
    files: [{ path: "examples/menu-demo.tsx", type: "registry:example" }],
    categories: ["menu"],
  },
  {
    name: "menu-group-labels",
    description: "Menu items grouped with labels",
    type: "registry:example",
    registryDependencies: ["@audio/menu", "@audio/button"],
    files: [
      { path: "examples/menu-group-labels.tsx", type: "registry:example" },
    ],
    categories: ["menu", "label"],
  },
  {
    name: "menu-hover",
    description: "Open the menu on hover",
    type: "registry:example",
    registryDependencies: ["@audio/menu", "@audio/button"],
    files: [{ path: "examples/menu-hover.tsx", type: "registry:example" }],
    categories: ["menu"],
  },
  {
    name: "menu-link",
    description: "Menu items as links",
    type: "registry:example",
    registryDependencies: ["@audio/menu", "@audio/button"],
    files: [{ path: "examples/menu-link.tsx", type: "registry:example" }],
    categories: ["menu", "link"],
  },
  {
    name: "menu-nested",
    description: "Menu with submenu",
    type: "registry:example",
    registryDependencies: ["@audio/menu", "@audio/button"],
    files: [{ path: "examples/menu-nested.tsx", type: "registry:example" }],
    categories: ["menu"],
  },
  {
    name: "menu-radio-group",
    description: "Menu with radio options",
    type: "registry:example",
    registryDependencies: ["@audio/menu", "@audio/button"],
    files: [
      { path: "examples/menu-radio-group.tsx", type: "registry:example" },
    ],
    categories: ["menu", "radio"],
  },
  {
    name: "meter-demo",
    description: "Basic meter",
    type: "registry:example",
    registryDependencies: ["@audio/meter"],
    files: [{ path: "examples/meter-demo.tsx", type: "registry:example" }],
    categories: ["meter"],
  },
  {
    name: "meter-simple",
    description: "Meter without label and value",
    type: "registry:example",
    registryDependencies: ["@audio/meter"],
    files: [{ path: "examples/meter-simple.tsx", type: "registry:example" }],
    categories: ["meter"],
  },
  {
    name: "meter-with-formatted-value",
    description: "Meter with a custom formatted value",
    type: "registry:example",
    registryDependencies: ["@audio/meter"],
    files: [
      {
        path: "examples/meter-with-formatted-value.tsx",
        type: "registry:example",
      },
    ],
    categories: ["meter"],
  },
  {
    name: "meter-with-range",
    description: "Meter with min and max values",
    type: "registry:example",
    registryDependencies: ["@audio/meter"],
    files: [
      { path: "examples/meter-with-range.tsx", type: "registry:example" },
    ],
    categories: ["meter"],
  },
  {
    name: "number-field-demo",
    description: "A number field",
    type: "registry:example",
    registryDependencies: ["@audio/number-field"],
    files: [
      { path: "examples/number-field-demo.tsx", type: "registry:example" },
    ],
    categories: ["number field"],
  },
  {
    name: "number-field-sm",
    description: "Small number field",
    type: "registry:example",
    registryDependencies: ["@audio/number-field"],
    files: [{ path: "examples/number-field-sm.tsx", type: "registry:example" }],
    categories: ["number field"],
  },
  {
    name: "number-field-lg",
    description: "Large number field",
    type: "registry:example",
    registryDependencies: ["@audio/number-field"],
    files: [{ path: "examples/number-field-lg.tsx", type: "registry:example" }],
    categories: ["number field"],
  },
  {
    name: "number-field-disabled",
    description: "A disabled number field",
    type: "registry:example",
    registryDependencies: ["@audio/number-field"],
    files: [
      { path: "examples/number-field-disabled.tsx", type: "registry:example" },
    ],
    categories: ["number field", "disabled", "label"],
  },
  {
    name: "number-field-form",
    description: "A number in a form",
    type: "registry:example",
    registryDependencies: [
      "@audio/number-field",
      "@audio/field",
      "@audio/form",
      "@audio/button",
    ],
    files: [
      { path: "examples/number-field-form.tsx", type: "registry:example" },
    ],
    categories: ["number field", "field", "form", "button"],
  },
  {
    name: "number-field-with-formatted-value",
    description: "A number field with formatted value",
    type: "registry:example",
    registryDependencies: ["@audio/number-field"],
    files: [
      {
        path: "examples/number-field-with-formatted-value.tsx",
        type: "registry:example",
      },
    ],
    categories: ["number field"],
  },
  {
    name: "number-field-with-label",
    description: "A number field with an external label",
    type: "registry:example",
    registryDependencies: ["@audio/number-field", "@audio/label"],
    files: [
      {
        path: "examples/number-field-with-label.tsx",
        type: "registry:example",
      },
    ],
    categories: ["number field", "label"],
  },
  {
    name: "number-field-with-range",
    description: "A number field with min/max constraints",
    type: "registry:example",
    registryDependencies: ["@audio/number-field"],
    files: [
      {
        path: "examples/number-field-with-range.tsx",
        type: "registry:example",
      },
    ],
    categories: ["number field", "range"],
  },
  {
    name: "number-field-with-scrub",
    description: "A number field with a scrub area",
    type: "registry:example",
    registryDependencies: ["@audio/number-field"],
    files: [
      {
        path: "examples/number-field-with-scrub.tsx",
        type: "registry:example",
      },
    ],
    categories: ["number field"],
  },
  {
    name: "number-field-with-step",
    description: "A number field with step",
    type: "registry:example",
    registryDependencies: ["@audio/number-field"],
    files: [
      { path: "examples/number-field-with-step.tsx", type: "registry:example" },
    ],
    categories: ["number field"],
  },
  {
    name: "pagination-demo",
    description: "Pagination example",
    type: "registry:example",
    registryDependencies: ["@audio/pagination"],
    files: [{ path: "examples/pagination-demo.tsx", type: "registry:example" }],
    categories: ["pagination"],
  },
  {
    name: "popover-demo",
    description: "Popover with a form",
    type: "registry:example",
    registryDependencies: [
      "@audio/popover",
      "@audio/button",
      "@audio/textarea",
      "@audio/form",
      "@audio/field",
    ],
    files: [{ path: "examples/popover-demo.tsx", type: "registry:example" }],
    categories: ["popover", "button", "textarea", "form", "field"],
  },
  {
    name: "popover-with-close",
    description: "Popover with close button",
    type: "registry:example",
    registryDependencies: ["@audio/popover", "@audio/button"],
    files: [
      { path: "examples/popover-with-close.tsx", type: "registry:example" },
    ],
    categories: ["popover", "button"],
  },
  {
    name: "preview-card-demo",
    description: "Preview card example",
    type: "registry:example",
    registryDependencies: ["@audio/preview-card", "@audio/button"],
    files: [
      { path: "examples/preview-card-demo.tsx", type: "registry:example" },
    ],
    categories: ["preview card", "button"],
  },
  {
    name: "progress-demo",
    description: "Animated progress bar",
    type: "registry:example",
    registryDependencies: ["@audio/progress"],
    files: [{ path: "examples/progress-demo.tsx", type: "registry:example" }],
    categories: ["progress"],
  },
  {
    name: "progress-with-formatted-value",
    description: "Progress with a custom formatted value",
    type: "registry:example",
    registryDependencies: ["@audio/progress"],
    files: [
      {
        path: "examples/progress-with-formatted-value.tsx",
        type: "registry:example",
      },
    ],
    categories: ["progress"],
  },
  {
    name: "progress-with-label-value",
    description: "Progress with label and value",
    type: "registry:example",
    registryDependencies: ["@audio/progress"],
    files: [
      {
        path: "examples/progress-with-label-value.tsx",
        type: "registry:example",
      },
    ],
    categories: ["progress", "label"],
  },
  {
    name: "radio-group-card",
    description: "Card-style radio options",
    type: "registry:example",
    registryDependencies: ["@audio/radio-group", "@audio/label"],
    files: [
      { path: "examples/radio-group-card.tsx", type: "registry:example" },
    ],
    categories: ["radio", "label"],
  },
  {
    name: "radio-group-demo",
    description: "Basic radio group",
    type: "registry:example",
    registryDependencies: ["@audio/radio-group", "@audio/label"],
    files: [
      { path: "examples/radio-group-demo.tsx", type: "registry:example" },
    ],
    categories: ["radio", "label"],
  },
  {
    name: "radio-group-disabled",
    description: "Radio group with one option disabled",
    type: "registry:example",
    registryDependencies: ["@audio/radio-group", "@audio/label"],
    files: [
      { path: "examples/radio-group-disabled.tsx", type: "registry:example" },
    ],
    categories: ["radio", "label"],
  },
  {
    name: "radio-group-form",
    description: "Radio group in a form",
    type: "registry:example",
    registryDependencies: [
      "@audio/radio-group",
      "@audio/field",
      "@audio/fieldset",
      "@audio/form",
      "@audio/button",
    ],
    files: [
      { path: "examples/radio-group-form.tsx", type: "registry:example" },
    ],
    categories: ["radio", "field", "fieldset", "form", "button"],
  },
  {
    name: "radio-group-with-description",
    description: "Radio options with helper text",
    type: "registry:example",
    registryDependencies: ["@audio/radio-group", "@audio/label"],
    files: [
      {
        path: "examples/radio-group-with-description.tsx",
        type: "registry:example",
      },
    ],
    categories: ["radio", "label", "helper", "hint"],
  },
  {
    name: "scroll-area-demo",
    description: "Scroll area - vertical",
    type: "registry:example",
    registryDependencies: ["@audio/scroll-area"],
    files: [
      {
        path: "examples/scroll-area-demo.tsx",
        type: "registry:example",
      },
    ],
    categories: ["scroll area"],
  },
  {
    name: "scroll-area-horizontal",
    description: "Scroll area - horizontal",
    type: "registry:example",
    registryDependencies: ["@audio/scroll-area"],
    files: [
      {
        path: "examples/scroll-area-horizontal.tsx",
        type: "registry:example",
      },
    ],
    categories: ["scroll area"],
  },
  {
    name: "scroll-area-both",
    description: "Scroll area - both horizontal and vertical",
    type: "registry:example",
    registryDependencies: ["@audio/scroll-area"],
    files: [
      {
        path: "examples/scroll-area-both.tsx",
        type: "registry:example",
      },
    ],
    categories: ["scroll area"],
  },
  {
    name: "select-demo",
    description: "A basic select",
    type: "registry:example",
    registryDependencies: ["@audio/select"],
    files: [{ path: "examples/select-demo.tsx", type: "registry:example" }],
    categories: ["select"],
  },
  {
    name: "select-sm",
    description: "A select with small size",
    type: "registry:example",
    registryDependencies: ["@audio/select"],
    files: [{ path: "examples/select-sm.tsx", type: "registry:example" }],
    categories: ["select"],
  },
  {
    name: "select-lg",
    description: "A select with large size",
    type: "registry:example",
    registryDependencies: ["@audio/select"],
    files: [{ path: "examples/select-lg.tsx", type: "registry:example" }],
    categories: ["select"],
  },
  {
    name: "select-disabled",
    description: "A disabled select",
    type: "registry:example",
    registryDependencies: ["@audio/select"],
    files: [{ path: "examples/select-disabled.tsx", type: "registry:example" }],
    categories: ["select", "disabled"],
  },
  {
    name: "select-without-alignment",
    description: "Select popup not aligned to trigger",
    type: "registry:example",
    registryDependencies: ["@audio/select"],
    files: [
      {
        path: "examples/select-without-alignment.tsx",
        type: "registry:example",
      },
    ],
    categories: ["select"],
  },
  {
    name: "select-with-groups",
    description: "Select items grouped with labels",
    type: "registry:example",
    registryDependencies: ["@audio/select"],
    files: [
      { path: "examples/select-with-groups.tsx", type: "registry:example" },
    ],
    categories: ["select"],
  },
  {
    name: "select-multiple",
    description: "Multiple selection with formatted value",
    type: "registry:example",
    registryDependencies: ["@audio/select"],
    files: [{ path: "examples/select-multiple.tsx", type: "registry:example" }],
    categories: ["select"],
  },
  {
    name: "select-form",
    description: "Select in a form",
    type: "registry:example",
    registryDependencies: [
      "@audio/button",
      "@audio/select",
      "@audio/form",
      "@audio/field",
    ],
    files: [{ path: "examples/select-form.tsx", type: "registry:example" }],
    categories: ["select", "form", "field", "helper", "hint"],
  },
  {
    name: "separator-demo",
    description: "Separator with horizontal and vertical orientations",
    type: "registry:example",
    registryDependencies: ["@audio/separator"],
    files: [{ path: "examples/separator-demo.tsx", type: "registry:example" }],
    categories: ["separator"],
  },
  {
    name: "spinner-demo",
    description: "Spinner demo",
    type: "registry:example",
    registryDependencies: ["@audio/spinner"],
    files: [{ path: "examples/spinner-demo.tsx", type: "registry:example" }],
    categories: ["spinner"],
  },
  {
    name: "skeleton-demo",
    description: "Skeleton demo",
    type: "registry:example",
    registryDependencies: ["@audio/cover", "@audio/button", "@audio/skeleton"],
    files: [{ path: "examples/skeleton-demo.tsx", type: "registry:example" }],
    categories: ["skeleton"],
  },
  {
    name: "skeleton-only",
    description: "Skeleton only",
    type: "registry:example",
    registryDependencies: ["@audio/skeleton"],
    files: [{ path: "examples/skeleton-only.tsx", type: "registry:example" }],
    categories: ["skeleton"],
  },
  {
    name: "slider-demo",
    description: "Basic slider",
    type: "registry:example",
    registryDependencies: ["@audio/slider"],
    files: [{ path: "examples/slider-demo.tsx", type: "registry:example" }],
    categories: ["slider"],
  },
  {
    name: "slider-with-label-value",
    description: "Slider with label and value",
    type: "registry:example",
    registryDependencies: ["@audio/slider", "@audio/label"],
    files: [
      {
        path: "examples/slider-with-label-value.tsx",
        type: "registry:example",
      },
    ],
    categories: ["slider", "label"],
  },
  {
    name: "slider-range",
    description: "Two-thumb range slider",
    type: "registry:example",
    registryDependencies: ["@audio/slider"],
    files: [{ path: "examples/slider-range.tsx", type: "registry:example" }],
    categories: ["slider", "range slider"],
  },
  {
    name: "slider-vertical",
    description: "Vertical slider",
    type: "registry:example",
    registryDependencies: ["@audio/slider"],
    files: [{ path: "examples/slider-vertical.tsx", type: "registry:example" }],
    categories: ["slider", "vertical slider"],
  },
  {
    name: "slider-form",
    description: "Slider in a form",
    type: "registry:example",
    registryDependencies: [
      "@audio/slider",
      "@audio/form",
      "@audio/field",
      "@audio/button",
    ],
    files: [{ path: "examples/slider-form.tsx", type: "registry:example" }],
    categories: ["slider", "form", "field", "button", "helper", "hint"],
  },
  {
    name: "switch-demo",
    description: "Basic switch",
    type: "registry:example",
    registryDependencies: ["@audio/switch", "@audio/label"],
    files: [{ path: "examples/switch-demo.tsx", type: "registry:example" }],
    categories: ["switch", "label"],
  },
  {
    name: "switch-disabled",
    description: "Disabled switch",
    type: "registry:example",
    registryDependencies: ["@audio/switch", "@audio/label"],
    files: [{ path: "examples/switch-disabled.tsx", type: "registry:example" }],
    categories: ["switch", "label", "disabled"],
  },
  {
    name: "switch-with-description",
    description: "Switch with description",
    type: "registry:example",
    registryDependencies: ["@audio/switch", "@audio/label"],
    files: [
      {
        path: "examples/switch-with-description.tsx",
        type: "registry:example",
      },
    ],
    categories: ["switch", "label", "helper", "hint"],
  },
  {
    name: "switch-card",
    description: "Card-style switch",
    type: "registry:example",
    registryDependencies: ["@audio/switch", "@audio/label"],
    files: [{ path: "examples/switch-card.tsx", type: "registry:example" }],
    categories: ["switch", "label", "card"],
  },
  {
    name: "switch-form",
    description: "Switch in a form",
    type: "registry:example",
    registryDependencies: [
      "@audio/switch",
      "@audio/field",
      "@audio/form",
      "@audio/button",
    ],
    files: [{ path: "examples/switch-form.tsx", type: "registry:example" }],
    categories: ["switch", "form", "field", "button"],
  },
  {
    name: "table-demo",
    description: "Basic table",
    type: "registry:example",
    registryDependencies: ["@audio/table", "@audio/badge"],
    files: [{ path: "examples/table-demo.tsx", type: "registry:example" }],
    categories: ["table", "badge"],
  },
  {
    name: "table-framed",
    description: "Framed table",
    type: "registry:example",
    registryDependencies: ["@audio/table", "@audio/badge", "@audio/frame"],
    files: [{ path: "examples/table-framed.tsx", type: "registry:example" }],
    categories: ["table", "badge", "frame"],
  },
  {
    name: "tabs-demo",
    description: "Tabs with default indicator",
    type: "registry:example",
    registryDependencies: ["@audio/tabs"],
    files: [{ path: "examples/tabs-demo.tsx", type: "registry:example" }],
    categories: ["tabs"],
  },
  {
    name: "tabs-underline",
    description: "Tabs with underline indicator",
    type: "registry:example",
    registryDependencies: ["@audio/tabs"],
    files: [{ path: "examples/tabs-underline.tsx", type: "registry:example" }],
    categories: ["tabs"],
  },
  {
    name: "tabs-vertical",
    description: "Tabs with vertical layout",
    type: "registry:example",
    registryDependencies: ["@audio/tabs"],
    files: [{ path: "examples/tabs-vertical.tsx", type: "registry:example" }],
    categories: ["tabs", "vertical tabs"],
  },
  {
    name: "tabs-underline-vertical",
    description: "Underline tabs with vertical layout",
    type: "registry:example",
    registryDependencies: ["@audio/tabs"],
    files: [
      {
        path: "examples/tabs-underline-vertical.tsx",
        type: "registry:example",
      },
    ],
    categories: ["tabs", "vertical tabs"],
  },
  {
    name: "textarea-demo",
    description: "Basic textarea",
    type: "registry:example",
    registryDependencies: ["@audio/textarea"],
    files: [{ path: "examples/textarea-demo.tsx", type: "registry:example" }],
    categories: ["textarea"],
  },
  {
    name: "textarea-sm",
    description: "Small textarea",
    type: "registry:example",
    registryDependencies: ["@audio/textarea"],
    files: [{ path: "examples/textarea-sm.tsx", type: "registry:example" }],
    categories: ["textarea"],
  },
  {
    name: "textarea-lg",
    description: "Large textarea",
    type: "registry:example",
    registryDependencies: ["@audio/textarea"],
    files: [{ path: "examples/textarea-lg.tsx", type: "registry:example" }],
    categories: ["textarea"],
  },
  {
    name: "textarea-disabled",
    description: "Disabled textarea",
    type: "registry:example",
    registryDependencies: ["@audio/textarea"],
    files: [
      { path: "examples/textarea-disabled.tsx", type: "registry:example" },
    ],
    categories: ["textarea", "disabled"],
  },
  {
    name: "textarea-with-label",
    description: "Textarea labelled with Field",
    type: "registry:example",
    registryDependencies: ["@audio/textarea", "@audio/label"],
    files: [
      { path: "examples/textarea-with-label.tsx", type: "registry:example" },
    ],
    categories: ["textarea", "field", "label"],
  },
  {
    name: "textarea-form",
    description: "Textarea in a form",
    type: "registry:example",
    registryDependencies: [
      "@audio/textarea",
      "@audio/form",
      "@audio/field",
      "@audio/button",
    ],
    files: [{ path: "examples/textarea-form.tsx", type: "registry:example" }],
    categories: ["textarea", "form", "field", "button"],
  },
  {
    name: "toast-demo",
    description: "Status toast",
    type: "registry:example",
    registryDependencies: ["@audio/toast"],
    files: [{ path: "examples/toast-demo.tsx", type: "registry:example" }],
    categories: ["toast", "button"],
  },
  {
    name: "toast-loading",
    description: "Loading toast",
    type: "registry:example",
    registryDependencies: ["@audio/toast"],
    files: [{ path: "examples/toast-loading.tsx", type: "registry:example" }],
    categories: ["toast", "button", "loading"],
  },
  {
    name: "toast-promise",
    description: "Drive toasts from promise states",
    type: "registry:example",
    registryDependencies: ["@audio/toast"],
    files: [{ path: "examples/toast-promise.tsx", type: "registry:example" }],
    categories: ["toast", "button"],
  },
  {
    name: "toast-with-action",
    description: "Toast with an action button",
    type: "registry:example",
    registryDependencies: ["@audio/toast"],
    files: [
      { path: "examples/toast-with-action.tsx", type: "registry:example" },
    ],
    categories: ["toast", "button"],
  },
  {
    name: "toast-with-status",
    description: "Success toast",
    type: "registry:example",
    registryDependencies: ["@audio/toast"],
    files: [
      { path: "examples/toast-with-status.tsx", type: "registry:example" },
    ],
    categories: ["toast", "button"],
  },
  {
    name: "toast-heights",
    description: "Toast with varying heights",
    type: "registry:example",
    registryDependencies: ["@audio/toast"],
    files: [{ path: "examples/toast-heights.tsx", type: "registry:example" }],
    categories: ["toast"],
  },
  {
    name: "toggle-demo",
    description: "Basic toggle",
    type: "registry:example",
    registryDependencies: ["@audio/toggle"],
    files: [{ path: "examples/toggle-demo.tsx", type: "registry:example" }],
    categories: ["toggle"],
  },
  {
    name: "toggle-disabled",
    description: "Disabled toggle",
    type: "registry:example",
    registryDependencies: ["@audio/toggle"],
    files: [{ path: "examples/toggle-disabled.tsx", type: "registry:example" }],
    categories: ["toggle", "disabled"],
  },
  {
    name: "toggle-group-demo",
    description: "Toggle group",
    type: "registry:example",
    registryDependencies: ["@audio/toggle-group"],
    files: [
      { path: "examples/toggle-group-demo.tsx", type: "registry:example" },
    ],
    categories: ["toggle group", "toggle"],
  },
  {
    name: "toggle-group-sm",
    description: "Toggle group with small toggles",
    type: "registry:example",
    registryDependencies: ["@audio/toggle-group"],
    files: [{ path: "examples/toggle-group-sm.tsx", type: "registry:example" }],
    categories: ["toggle group", "toggle"],
  },
  {
    name: "toggle-group-lg",
    description: "Toggle group with large toggles",
    type: "registry:example",
    registryDependencies: ["@audio/toggle-group"],
    files: [{ path: "examples/toggle-group-lg.tsx", type: "registry:example" }],
    categories: ["toggle group", "toggle"],
  },
  {
    name: "toggle-group-outline",
    description: "Toggle group with outline toggles",
    type: "registry:example",
    registryDependencies: ["@audio/toggle-group"],
    files: [
      { path: "examples/toggle-group-outline.tsx", type: "registry:example" },
    ],
    categories: ["toggle group", "toggle"],
  },
  {
    name: "toggle-group-outline-with-separator",
    description: "Toggle group with outline toggles and separator",
    type: "registry:example",
    registryDependencies: ["@audio/toggle-group"],
    files: [
      {
        path: "examples/toggle-group-outline-with-separator.tsx",
        type: "registry:example",
      },
    ],
    categories: ["toggle group", "toggle"],
  },
  {
    name: "toggle-group-disabled",
    description: "Disabled toggle group",
    type: "registry:example",
    registryDependencies: ["@audio/toggle-group"],
    files: [
      { path: "examples/toggle-group-disabled.tsx", type: "registry:example" },
    ],
    categories: ["toggle group", "toggle", "disabled"],
  },
  {
    name: "toggle-group-multiple",
    description: "Toggle group with multiple selection",
    type: "registry:example",
    registryDependencies: ["@audio/toggle-group"],
    files: [
      { path: "examples/toggle-group-multiple.tsx", type: "registry:example" },
    ],
    categories: ["toggle group", "toggle"],
  },
  {
    name: "toggle-group-with-disabled-item",
    description: "Toggle group with disabled item",
    type: "registry:example",
    registryDependencies: ["@audio/toggle-group"],
    files: [
      {
        path: "examples/toggle-group-with-disabled-item.tsx",
        type: "registry:example",
      },
    ],
    categories: ["toggle group", "toggle", "disabled"],
  },
  {
    name: "toggle-icon-group",
    description: "Multiple toggles",
    type: "registry:example",
    registryDependencies: ["@audio/toggle"],
    files: [
      { path: "examples/toggle-icon-group.tsx", type: "registry:example" },
    ],
    categories: ["toggle"],
  },
  {
    name: "toggle-lg",
    description: "Large toggle",
    type: "registry:example",
    registryDependencies: ["@audio/toggle"],
    files: [{ path: "examples/toggle-lg.tsx", type: "registry:example" }],
    categories: ["toggle"],
  },
  {
    name: "toggle-outline",
    description: "Outline toggle",
    type: "registry:example",
    registryDependencies: ["@audio/toggle"],
    files: [{ path: "examples/toggle-outline.tsx", type: "registry:example" }],
    categories: ["toggle"],
  },
  {
    name: "toggle-sm",
    description: "Small toggle",
    type: "registry:example",
    registryDependencies: ["@audio/toggle"],
    files: [{ path: "examples/toggle-sm.tsx", type: "registry:example" }],
    categories: ["toggle"],
  },
  {
    name: "toggle-with-icon",
    description: "Toggle with icon",
    type: "registry:example",
    registryDependencies: ["@audio/toggle"],
    files: [
      { path: "examples/toggle-with-icon.tsx", type: "registry:example" },
    ],
    categories: ["toggle"],
  },
  {
    name: "toolbar-demo",
    description: "Toolbar",
    type: "registry:example",
    registryDependencies: [
      "@audio/button",
      "@audio/select",
      "@audio/toggle-group",
      "@audio/toolbar",
      "@audio/tooltip",
    ],
    files: [{ path: "examples/toolbar-demo.tsx", type: "registry:example" }],
    categories: ["toolbar", "button", "select", "toggle", "tooltip"],
  },
  {
    name: "tooltip-demo",
    description: "Basic tooltip",
    type: "registry:example",
    registryDependencies: ["@audio/tooltip", "@audio/button"],
    files: [{ path: "examples/tooltip-demo.tsx", type: "registry:example" }],
    categories: ["tooltip", "button"],
  },
  {
    name: "tooltip-grouped",
    description: "Toggle group with grouped tooltips",
    type: "registry:example",
    registryDependencies: ["@audio/tooltip", "@audio/toggle-group"],
    files: [{ path: "examples/tooltip-grouped.tsx", type: "registry:example" }],
    categories: ["tooltip", "toggle group", "toggle"],
  },
];
