
/** biome-ignore-all lint/suspicious/noExplicitAny: we use any to avoid type errors */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import React from "react" 

export const Index: Record<string, any> = {
  "ui": {
    name: "ui",
    description: "",
    type: "registry:ui",
    registryDependencies: ["@audio/player"],
    files: [undefined],
    component: null,
    categories: undefined,
    meta: undefined,
  },
  "slider": {
    name: "slider",
    description: "",
    type: "registry:ui",
    registryDependencies: [],
    files: [{
      path: "src/registry/default/ui/slider.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/slider.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "empty": {
    name: "empty",
    description: "",
    type: "registry:ui",
    registryDependencies: [],
    files: [{
      path: "src/registry/default/ui/empty.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/empty.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "sortable-list": {
    name: "sortable-list",
    description: "",
    type: "registry:ui",
    registryDependencies: ["@shadcn/button"],
    files: [{
      path: "src/registry/default/ui/sortable-list.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/sortable-list.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "player": {
    name: "player",
    description: "",
    type: "registry:ui",
    registryDependencies: ["@audio/store","@audio/audio","@audio/slider","@shadcn/empty","@shadcn/button","@shadcn/dialog","@shadcn/dropdown-menu","@shadcn/input","@shadcn/item","@shadcn/scroll-area","@shadcn/toggle","@shadcn/tooltip"],
    files: [{
      path: "src/registry/default/ui/audio/player.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/audio/player.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "track": {
    name: "track",
    description: "",
    type: "registry:ui",
    registryDependencies: ["@audio/sortable-list","@shadcn/empty","@shadcn/avatar","@shadcn/button","@shadcn/item","@shadcn/scroll-area"],
    files: [{
      path: "src/registry/default/ui/audio/track.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/audio/track.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "queue": {
    name: "queue",
    description: "",
    type: "registry:ui",
    registryDependencies: ["@audio/store","@audio/track","@shadcn/empty","@shadcn/button","@shadcn/command","@shadcn/dialog","@shadcn/dropdown-menu","@shadcn/input","@shadcn/item","@shadcn/scroll-area","@shadcn/toggle","@shadcn/tooltip"],
    files: [{
      path: "src/registry/default/ui/audio/queue.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/audio/queue.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "provider": {
    name: "provider",
    description: "",
    type: "registry:ui",
    registryDependencies: ["@audio/store","@audio/audio"],
    files: [{
      path: "src/registry/default/ui/audio/provider.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/audio/provider.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "player-demo": {
    name: "player-demo",
    description: "Audio player demo",
    type: "registry:example",
    registryDependencies: ["@audio/player","@audio/frame"],
    files: [{
      path: "src/registry/default/examples/player-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/examples/player-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["player"],
    meta: undefined,
  },
  "player-queue-demo": {
    name: "player-queue-demo",
    description: "Audio player with queue demo",
    type: "registry:example",
    registryDependencies: ["@audio/player","@audio/queue"],
    files: [{
      path: "src/registry/default/examples/player-queue-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/examples/player-queue-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["player","queue"],
    meta: undefined,
  },
  "player-stacked-demo": {
    name: "player-stacked-demo",
    description: "Audio player with stacked layout",
    type: "registry:example",
    registryDependencies: ["@audio/player"],
    files: [{
      path: "src/registry/default/examples/player-stacked-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/examples/player-stacked-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["player"],
    meta: undefined,
  },
  "queue-shuffle-repeat-demo": {
    name: "queue-shuffle-repeat-demo",
    description: "Minimal queue with shuffle and repeat controls",
    type: "registry:example",
    registryDependencies: ["@audio/player","@audio/queue"],
    files: [{
      path: "src/registry/default/examples/queue-shuffle-repeat-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/examples/queue-shuffle-repeat-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["queue"],
    meta: undefined,
  },
  "queue-preferences-demo": {
    name: "queue-preferences-demo",
    description: "Minimal queue with preferences dropdown",
    type: "registry:example",
    registryDependencies: ["@audio/player","@audio/queue"],
    files: [{
      path: "src/registry/default/examples/queue-preferences-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/examples/queue-preferences-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["queue"],
    meta: undefined,
  },
  "queue-all-controls-demo": {
    name: "queue-all-controls-demo",
    description: "Queue with all controls (shuffle, repeat, preferences)",
    type: "registry:example",
    registryDependencies: ["@audio/player","@audio/queue"],
    files: [{
      path: "src/registry/default/examples/queue-all-controls-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/examples/queue-all-controls-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["queue"],
    meta: undefined,
  },
  "track-demo": {
    name: "track-demo",
    description: "Minimal track component example",
    type: "registry:example",
    registryDependencies: ["@audio/player","@audio/track"],
    files: [{
      path: "src/registry/default/examples/track-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/examples/track-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["track"],
    meta: undefined,
  },
  "track-list-demo": {
    name: "track-list-demo",
    description: "Track list with selection example",
    type: "registry:example",
    registryDependencies: ["@audio/player","@audio/track"],
    files: [{
      path: "src/registry/default/examples/track-list-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/examples/track-list-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["track"],
    meta: undefined,
  },
  "track-list-grid-demo": {
    name: "track-list-grid-demo",
    description: "Track list with grid layout example",
    type: "registry:example",
    registryDependencies: ["@audio/player","@audio/track"],
    files: [{
      path: "src/registry/default/examples/track-list-grid-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/examples/track-list-grid-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["track","grid"],
    meta: undefined,
  },
  "track-sortable-list-demo": {
    name: "track-sortable-list-demo",
    description: "Track list with sortable selection example",
    type: "registry:example",
    registryDependencies: ["@audio/player","@audio/track"],
    files: [{
      path: "src/registry/default/examples/track-sortable-list-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/examples/track-sortable-list-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["track","sortable"],
    meta: undefined,
  },
  "track-sortable-list-grid-demo": {
    name: "track-sortable-list-grid-demo",
    description: "Track list with sortable selection and grid layout example",
    type: "registry:example",
    registryDependencies: ["@audio/player","@audio/track"],
    files: [{
      path: "src/registry/default/examples/track-sortable-list-grid-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/examples/track-sortable-list-grid-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["track","sortable","grid"],
    meta: undefined,
  },
  "particle-player": {
    name: "particle-player",
    description: "Audio player",
    type: "registry:block",
    registryDependencies: ["@audio/player","@audio/queue","@audio/store","@audio/audio"],
    files: [{
      path: "src/registry/default/particles/particle-player.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/particles/particle-player.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["player","queue"],
    meta: undefined,
  },
  "particle-player-widget": {
    name: "particle-player-widget",
    description: "Audio player widget",
    type: "registry:block",
    registryDependencies: ["@audio/player","@audio/track","@audio/store","@audio/audio"],
    files: [{
      path: "src/registry/default/particles/particle-player-widget.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/particles/particle-player-widget.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["player","widget"],
    meta: undefined,
  },
  "hooks": {
    name: "hooks",
    description: "",
    type: "registry:hook",
    registryDependencies: [],
    files: [undefined],
    component: null,
    categories: undefined,
    meta: undefined,
  },
  "lib": {
    name: "lib",
    description: "",
    type: "registry:lib",
    registryDependencies: ["@audio/store","@audio/audio"],
    files: [undefined],
    component: null,
    categories: undefined,
    meta: undefined,
  },
  "audio": {
    name: "audio",
    description: "Audio Lib",
    type: "registry:lib",
    registryDependencies: [],
    files: [{
      path: "src/registry/default/lib/audio.ts",
      type: "registry:lib",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/lib/audio.ts")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["lib","audio"],
    meta: undefined,
  },
  "store": {
    name: "store",
    description: "Audio store",
    type: "registry:lib",
    registryDependencies: ["@audio/audio"],
    files: [{
      path: "src/registry/default/lib/audio-store.ts",
      type: "registry:lib",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/lib/audio-store.ts")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["lib","audio","store"],
    meta: undefined,
  },
  }